### ISSUE TITLE
Error during RNA-Star index generation due to use of the parent (..) path expression

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/cloudbiolinux#189]
I have serious issues when generating STAR indexes (by [cloudbio.biodata.genomes](https://github.com/chapmanb/cloudbiolinux/blob/master/cloudbio/biodata/genomes.py#L669)) due to the use of the parent (`..`) expression in the path of the parameter `--genomedir`. Effectively, this leads to parameters supplied to the `STAR` command in the form of `/bcbio/lib/genomes/Mmusculus/mm10/seq/../star.` (note the `..` at the end). Appearently this expression is not well understood by `STAR` and/or the cluster file system we are using (glusterFS). As a result, `STAR` stalls when writing the SA indexes. All works fine if  `--genomedir` is supplied without the parent expression. 

Since the use of the parent expression is not strictly required (one could use Python functions to parse the path and find the parent directory) I suggest that this somewhat unpythonic way of constructing the `--genomedir` path and other `STAR `paths in the same function should be changed. In addition, I note that the same function does not make use of the `--runThreadN <NUMCORES>` parameter which can drastically speed up index generation, see the [bcbio implementation](https://github.com/chapmanb/bcbio-nextgen/blob/3c378b695c6a2d9be9ae8117610bcbec00066519/bcbio/ngsalign/star.py#L108). I suggest that the command could use all available cores on the machine.

**Comment by roryk** [comment]
Hi Eric,

Thanks for the note and the detailed debugging, it is super, super helpful. I modified the cloudbiolinux code to normalize the genome path so the .. isn't in it anymore and added in some logic to use all of the available CPU cores to generate the STAR index. I tested it and it seems to work okay, feel free to reopen if it ends up not working for you though. Thanks again!
