### ISSUE TITLE
prepare_tx_gff.py and gtfToGenePred

### ISSUE THREAD

**Issue by danhalligan** [chapmanb/cloudbiolinux#190]
It seems that `prepare_tx_gff.py` depends on gtfToGenePred being available in the users path.

**Comment by danhalligan** [comment]
Actually I think I just noticed that this will get installed only if twoBitToFa is not installed. On my system I had twoBitToFa installed but not gtfToGenePred. So, this bug is particular to my system, but seems slightly fragile.

**Comment by roryk** [comment]
Hi Dan,

Thanks for pointing this weakness. I pushed a change to check for lists of programs instead of just one, and added gtfToGenePred to the list to check on install which should guarantee gtfToGenePred gets installed in the future.

**Comment by danhalligan** [comment]
Thanks!
