### ISSUE TITLE
cmake download broken

### ISSUE THREAD

**Issue by mdeboth** [chapmanb/cloudbiolinux#191]
Similar problem to #186 - I think the recent release of cmake 3.2.2 is causing a problem?
```
--2015-04-15 22:41:42--  https://s3.amazonaws.com/cloudbiolinux/brew_bottles/cmake-3.2.2.x86_64-linux.bottle.tar.gz
Resolving s3.amazonaws.com... 54.231.13.72
Connecting to s3.amazonaws.com|54.231.13.72|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-04-15 22:41:42 ERROR 404: Not Found.
```

**Comment by chapmanb** [comment]
Matt;
Thanks for the heads up. I pushed a new cmake bottle so you shouldn't get this message any longer. CloudBioLinux should recover gracefully from this and build a local package if it can't find the bottle. If it is erroring out for you happy to dig into that more so we don't get failures on new updates. Thanks again for letting us know.

**Comment by mdeboth** [comment]
Working now... I think the local build failure was caused by a Ruby dependency problem on my end & shouldn't be an issue. Thanks, Brad!
