### ISSUE TITLE
Unattended install hangs due to cloud-init config

### ISSUE THREAD

**Issue by kdaily** [chapmanb/cloudbiolinux#193]
I'm installing cloudbiolinux `ngs_pipeline_minimal` on the StarCluster Ubuntu 12.04 Amazon AMI (ami-765b3e1f in US-east region). When it tries to install `cloud-init` there seems to be a configuration file conflict. During an unattended install this is a problem. 

```
> fab -f fabfile.py -H localhost install_biolinux:flavor=ngs_pipeline_minimal
.......... # Lots of stuff.........

Setting up cloud-init (0.6.3-0ubuntu1.17) ...

Configuration file `/etc/cloud/cloud.cfg'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
```

Some research shows that I can do the following in an `apt-get` call to handle this:

```
export DEBIAN_FRONTEND=noninteractive
apt-get -o Dpkg::Options::="--force-confnew" install -y cloud-init
```

Is there any way to pass these `apt-get` parameters on?

**Comment by kdaily** [comment]
It's because there is a version of `cloud-init` installed in this StarCluster AMI (0.6.3-0ubuntu1.5) while an `apt-get upgrade` gets a new version (0.6.3-0ubuntu1.17). I suppose the sensible thing to do is to upgrade this package prior to the `fabric` run.

**Comment by chapmanb** [comment]
Kenneth;
Thanks for trying this all out. I've also done CloudBioLinux on top of Starcluster work and it is probably not the best way to go to get the tools installed. They both use SGE and cloud-init and other parts that can conflict with each other.

If your goal is to get biological tools on a Starcluster instance, your best bet would be to use the bcbio installer, which makes use of everything in `ngs_pipeline_minimal` but doesn't try to do any of the system parts which could conflict:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#automated

You can run the installer with `--nodata` to skip the data downloads and just get all the tools installed. Hope this approach works for what you need.

**Comment by kdaily** [comment]
Thanks for that suggestion of bcbio - I'll see if that streamlines things!

**Comment by kdaily** [comment]
Using the `bcbio_nextgen_install.py` has the same issue when it gets to `cloud-init`! D'oh! Guess my only way is to upgrade it first before hand.

**Comment by chapmanb** [comment]
Kenneth;
Sorry about the issue, I had thought about running bcbio_nextgen.py without the sudo option so it didn't touch system packages, but it is also pretty intrusive to upgrade all the system packages. I pushed a fix to skip this for `ngs_pipeline_minimal`/bcbio installs so it hopefully should avoid trying to adjust `cloud_init` and not have this issue.

Please feel free to re-open if you run into anything else -- happy to debug more issues to get it working for your use case.

**Comment by kdaily** [comment]
Thanks, will try it out!

**Comment by kdaily** [comment]
I got this now, unsure if it's related to not doing upgrad to system packages (tried on two instances, m3.medium and m3.xlarge):

```
Collecting pycurl>=7.19.5.1 (from arvados-python-client>=0.1.1405019228.4a7ca04->-r https://raw.github.com/chapmanb/bcbio-nextgen/master/requirements.txt (line 19))
  Downloading pycurl-7.19.5.1.tar.gz (142kB)
    100% |████████████████████████████████| 143kB 1.0MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-JIYiUy/pycurl/setup.py", line 634, in <module>
        ext = get_extension(split_extension_source=split_extension_source)
      File "/tmp/pip-build-JIYiUy/pycurl/setup.py", line 392, in get_extension
        ext_config = ExtensionConfiguration()
      File "/tmp/pip-build-JIYiUy/pycurl/setup.py", line 65, in __init__
        self.configure()
      File "/tmp/pip-build-JIYiUy/pycurl/setup.py", line 100, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-JIYiUy/pycurl
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 261, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 36, in main
    bcbio = bootstrap_bcbionextgen(anaconda, args, remotes)
  File "bcbio_nextgen_install.py", line 73, in bootstrap_bcbionextgen
    subprocess.check_call([anaconda["pip"], "install", "-r", remotes["requirements"]])
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/pip', 'install', '-r', 'https://raw.github.com/chapmanb/bcbio-nextgen/master/requirements.txt']' returned non-zero exit status 1
```

Which means I needed to do this first:

```
apt-get install libcurl3 libcurl3-dev
```

This is a hard problem to solve - balance between conveniently auto-installing everything, and being able to work on arbitrary systems. I'm OK with these workarounds, but might be useful for someone else to know what could be problematic!

**Comment by chapmanb** [comment]
Kenneth;
Thanks for this. Apologies, the curl/PyCurl dependency is new and we hadn't run into this yet. I'd rather not depend on a curl library here so removed it at this point and I'll re-add it as a conda package. If you re-try now it should hopefully go cleanly without needing the additional libraries.

More generally, this is how we bootstrap a bare system to install this on Docker, which might be helpful as a starting point:

https://github.com/chapmanb/bcbio-nextgen/blob/master/Dockerfile#L5

Thanks again for all the patience working through the automated install.

**Comment by kdaily** [comment]
Thanks - that looks quite a bit like my Packer script. I'll poke through it some more though.
