### ISSUE TITLE
Outdated path to dbSNP on ncbi ftp server

### ISSUE THREAD

**Issue by mpschr** [chapmanb/cloudbiolinux#196]
Hi

The path both dnsnp-142 is outdated. [hg38/dbsnp-142.yaml](https://github.com/chapmanb/cloudbiolinux/blob/edfda6b/ggd-recipes/hg38-noalt/dbsnp-142.yaml#L15) & [hg38-noalt/dbsnp-142.yaml](https://github.com/chapmanb/cloudbiolinux/blob/edfda6b0260b5af75fc78edcadd68cdd4ca52726/ggd-recipes/hg38-noalt/dbsnp-142.yaml#L15).

During installation, the script tries to download the following file: `ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/All_20150416.vcf.gz` which is not available.

Either the file is here: `ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b142_GRCh38/VCF` or the newer version is called `All_20150603.vcf.gz` and is found here: `ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/All_20150603.vcf.gz`

I *guess* that `All_20150603` version already version 144 Altough the date doesn't exactly match the info found here: http://www.ncbi.nlm.nih.gov/projects/SNP/snp_summary.cgi?view+summary=view+summary&build_id=144.

**Comment by chapmanb** [comment]
Michael;
Thanks much for the heads up on the problem. You're exactly right, the 144 release changed the directory structure. I pushed fixes to update to 144 and try and generalize the formula so it will be stable across new releases. Please let us know if you run into anything else at all. Thanks again.

**Comment by mpschr** [comment]
Great! Thanks for the quick fix, now the download works fine.
