### ISSUE TITLE
Unable to 'install' star index for hg38

### ISSUE THREAD

**Issue by mpschr** [chapmanb/cloudbiolinux#197]
Apparently, the installation skipped the step of preparing or downloading the star index. I tried to 'upgrade' to it, with the following command:

```bcbio_nextgen.py upgrade --aligners star --genomes hg38 --data```

First it fails at GGD (I am not sure what this is) and then as backup, it tries to download an image from amazon, which cannot be found (404).

In the end, it doesnt find the rnaseq folder. Where should this come from?

The output is the following:

```
Upgrading bcbio-nextgen data files
Cloning into 'cloudbiolinux'...
remote: Counting objects: 10937, done.
remote: Total 10937 (delta 0), reused 0 (delta 0), pack-reused 10937
Receiving objects: 100% (10937/10937), 7.61 MiB | 2.26 MiB/s, done.
Resolving deltas: 100% (6069/6069), done.
Checking connectivity... done.
Setting up virtual machine
INFO: <cloudbio.flavor.Flavor instance at 0x7f3e9ba785f0>
INFO: This is a ngs_pipeline_minimal flavor
INFO: Reading default fabricrc.txt
DBG [config.py]: Using config file /home/michael/bin/tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
INFO: Distribution __auto__
INFO: Get local environment
[localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
INFO: Ubuntu setup
DBG [distribution.py]: Debian-shared setup
DBG [distribution.py]: Source=trusty
DBG [distribution.py]: Checking target distribution ubuntu
[localhost] local: cat /proc/version
[localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
DBG [distribution.py]: NixPkgs: Ignored
[localhost] local: echo $HOME
[localhost] local: uname -m
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['star', 'bwa'], 'genomes': [{'name': 'Human (hg38) full', 'dbkey': 'hg38', 'annotations': ['dbsnp', 'clinvar', 'mills_indels', '1000g_snps', '1000g_indels', '1000g_omni_snps', 'hapmap_snps']}], 'install_uniref': False}'): Human (hg38) full
INFO: Genome preparation method ggd failed, trying next
INFO: Downloading genome from s3: hg38 star
[localhost] local: pwd
[localhost] local: echo $HOME
[localhost] local: wget --continue --no-check-certificate -O hg38-star.tar.xz 'https://s3.amazonaws.com/biodata/genomes/hg38-star.tar.xz'
--2015-06-15 10:09:55--  https://s3.amazonaws.com/biodata/genomes/hg38-star.tar.xz
Resolving proxy.sth.de (proxy.sth.de)... 141.42.1.215
Connecting to proxy.sth.de (proxy.sth.de)|141.42.1.215|:8080... connected.
Proxy request sent, awaiting response... 404 Not Found
2015-06-15 10:09:56 ERROR 404: Not Found.


Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O hg38-star.tar.xz 'https://s3.amazonaws.com/biodata/genomes/hg38-star.tar.xz''

INFO: Genome preparation method s3 failed, trying next
INFO: Preparing genome hg38 with index star
/home/michael/bin/bcbionextgen/data/genomes/Hsapiens/hg38/seq/../rnaseq/ref-transcripts.gtf not found, skipping creating the STAR index.
/home/michael/bin/bcbionextgen/data/genomes/Hsapiens/hg38/seq/../rnaseq/ref-transcripts.gtf not found, skipping creating the STAR index.
bcbio-nextgen data upgrade complete.
Upgrade completed successfully.
```

**Comment by chapmanb** [comment]
Michael;
Sorry about the issues. We don't yet support RNA-seq analysis on hg38, which is the source of your failure. hg38 is still a work in progress and here's a bit more detail on the current status:

https://github.com/chapmanb/bcbio-nextgen/issues/817#issuecomment-100679752

We definitely want to do this, but still have to make some time to prepare and validate the transcript files.

**Comment by mpschr** [comment]
Hi Brad

What would be your suggestion? Get a GTF file myself or switch to another build? I think I could just go to download the gtf file myself (e.g. from gencode) and place it in the folder `/home/michael/bin/bcbionextgen/data/genomes/Hsapiens/hg38/seq/../rnaseq/ref-transcripts.gtf`. Or will I be mixing data sources which shouldnt be mixed?

**Comment by chapmanb** [comment]
Michael;
Do you need build 38 for a specific reason? If not, the best approach is to use 37 (GRCh37 or hg19) until there are more resources for 38 in place. I'm a big fan of the new build but it will take some time to support and validate that all tools work as expected. Hope this helps.

**Comment by mpschr** [comment]
Ok, thanks for your answer. It's not a necessity so I can live with the option of using GRCh37, especially seeing that some tools do not support yet build 38 yet (e.g. CADD). 

I understand that it is a huge amount of work checking if all the installed libraries and tools are compatible with build 38 - so first thanks for the effort. Is there also a checklist/site where the already validated tools are documented? 

Michael

**Comment by chapmanb** [comment]
Michael -- the thread I linked to earlier is where we're documenting/discussing what works and doesn't:

https://github.com/chapmanb/bcbio-nextgen/issues/817

We don't have anything more official, but generally I'd treat 38 as a work in progress and only use it if you have interest in debugging tools. We'll have more documentation when we validate/support a larger subsection of 38 but are moving our way there. Hope this helps.
