### ISSUE TITLE
install fails on ubuntu server x64 14.02 LTS

### ISSUE THREAD

**Issue by alexstaj** [chapmanb/cloudbiolinux#198]
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Ign http://research.cs.wisc.edu squeeze/contrib Translation-en
Fetched 1,001 kB in 5s (192 kB/s)            
Reading package lists... Done
W: GPG error: http://research.cs.wisc.edu squeeze InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 973FC7D2670079F6
W: GPG error: http://ppa.launchpad.net trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 759A8E0E5BA15160
DBG [config.py]: Using config file /home/staj/tools/cloudbiolinux/cloudbio/../config/packages.yaml
[localhost] local: sudo http_proxy=$http_proxy https_proxy=$https_proxy  bash -c "apt-get -y --force-yes upgrade"
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  linux-headers-generic-lts-utopic linux-signed-generic-lts-utopic
  linux-signed-image-generic-lts-utopic python-paramiko
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
INFO: Reading /home/staj/tools/cloudbiolinux/cloudbio/../config/packages.yaml
DBG [shared.py]: Packages to install: euca2ools,s3cmd,bio-linux-dotter,bio-linux-mcl,bio-linux-mummer,bio-linux-pfaat,bio-linux-prank,bio-linux-squint,bio-linux-t-coffee,exonerate,mafft,muscle,probcons,wise,bio-linux-artemis,bio-linux-big-blast,bio-linux-cd-hit,bio-linux-rbs-finder,bio-linux-transterm-hp,mcl,predictprotein,tigr-glimmer,bio-linux-catchall,bio-linux-readseq,primer3,ugene,bio-linux-oligoarray,bio-linux-oligoarrayaux,fastx-toolkit,last-align,maq,plink,tabix,bio-linux-blast,bio-linux-blixem,bio-linux-fasta,bio-linux-hmmer,bio-linux-mspcrunch,bio-linux-mview,blast2,cdbfasta,ncbi-tools-bin,bio-linux-cap3,bio-linux-tablet,bio-linux-bldp-files,bio-linux-genquery,bio-linux-keyring,bio-linux-sampledata,bio-linux-taxinspector,rasmol,libmysqlclient15-dev,mysql-client,mysql-common,mysql-server,libpq-dev,postgresql,postgresql-client,postgresql-plperl-9.3,postgresql-plpython-9.3,couchdb,libdb-dev,libtokyocabinet-dev,mongodb,tokyocabinet-bin,libsqlite0,libsqlite0-dev,libsqlite3-0,libsqlite3-dev,sqlite3,libhdf5-serial-dev,bio-linux-tutorials,cloudbl-desktop,evince,firefox,gdm,gnome-backgrounds,gnome-panel,gnome-system-tools,gnome-terminal,software-center,synaptic,ubuntu-desktop,xvfb,libfuse-dev,libopenmpi-dev,libzmq-dev,nfs-common,nfs-kernel-server,openmpi-bin,rabbitmq-server,texlive-latex-base,texlive-latex-extra,texlive-latex-recommended,erlang,erlang-base,erlang-dev,erlang-examples,erlang-manpages,erlang-mode,c2hs,cabal-install,ghc,openjdk-7-jdk,openjdk-7-jre,ant,jruby,jython,libbiojava-java,libbiojava-java-demos,libjhdf5-java,libjline-java,maven2,openjdk-6-jdk,openjdk-6-jre,scala,scala-library,gsl-bin,libatlas-base-dev,libblas-dev,libbz2-dev,libc6-dev,libcurl4-openssl-dev,libeigen3-dev,libgsl0-dev,libgsl0ldbl,liblapack-dev,liblzma-dev,libncurses5-dev,libnetcdf-dev,libpcre3-dev,libpng12-dev,libreadline-dev,libssl-dev,libxml2,libxml2-dev,libxslt1-dev,libxslt1.1,libzip-dev,mime-support,uuid,uuid-dev,xz-utils,zlib1g-dev,zlib1g-dev,octave,prover9,bsdmainutils,clang,cmake,g++,gcc,gfortran,libtool,make,patch,pkg-config,vim,htop,sudo,bzr,cvs,git-core,mercurial,subversion,curl,wget,axel,gawk,less,openssh-server,pigz,rsync,screen,unzip,cpanminus,libextutils-autoinstall-perl,libperl-dev,parrot,parrot-devel,perl,perl-modules,perl-tk,bio-linux-fasttree,bio-linux-archaeopteryx,bio-linux-cytoscape,bio-linux-dendroscope,bio-linux-fastdnaml,bio-linux-mesquite,bio-linux-mrbayes,bio-linux-omegamap,bio-linux-qtlcart,bio-linux-treeview,mrbayes,njplot,phyml,tree-puzzle,libfuse-dev,libgtk2.0-dev,protobuf-compiler,python-software-properties,rsync,stow,swig,xfsprogs,build-essential,debhelper,devscripts,dh-make,pbuilder,unzip,dkms,emacs,emacs-goodies-el,emacsen-common,exuberant-ctags,gedit,imagemagick,libboost-dev,libboost-python-dev,libboost-thread-dev,libgd2-xpm-dev,libgnomecanvas2-0,libgnomecanvas2-dev,libgnomeui-0,libgnomeui-dev,libgnomevfs2-0,libgnomevfs2-dev,libpango1.0-0,libpango1.0-dev,libsparsehash-dev,libx11-dev,pdfjam,tcl-dev,tk-dev,xvfb,lynx,traceroute,fdupes,mc,screen,time,tree,aspell,dictionaries-common,libaspell-dev,python,python-dev,python-distutils-extra,python-pip,python-rpy,python-setuptools,python-virtualenv,python3,python3-dev,r-base,r-base-core,r-base-dev,ruby1.9.1,ruby1.9.1-dev,gnuplot,graphviz,imagemagick,libgl1-mesa-dev,libgl1-mesa-dri,libgl1-mesa-glx,libglu1-mesa,libglu1-mesa-dev,libgraphviz-dev,mayavi2,mtasc,x11-apps,apache2
INFO: Installing 272 packages
INFO: Package install progress: 0/272
[localhost] local: sudo http_proxy=$http_proxy https_proxy=$https_proxy  bash -c "apt-get -y --force-yes install euca2ools s3cmd bio-linux-dotter bio-linux-mcl bio-linux-mummer bio-linux-pfaat bio-linux-prank bio-linux-squint bio-linux-t-coffee exonerate mafft muscle probcons wise bio-linux-artemis bio-linux-big-blast bio-linux-cd-hit bio-linux-rbs-finder bio-linux-transterm-hp mcl predictprotein tigr-glimmer bio-linux-catchall bio-linux-readseq primer3 ugene bio-linux-oligoarray bio-linux-oligoarrayaux fastx-toolkit last-align"
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package bio-linux-dotter
E: Unable to locate package bio-linux-mcl
E: Unable to locate package bio-linux-mummer
E: Unable to locate package bio-linux-pfaat
E: Unable to locate package bio-linux-prank
E: Unable to locate package bio-linux-squint
E: Unable to locate package bio-linux-t-coffee
E: Unable to locate package bio-linux-artemis
E: Unable to locate package bio-linux-big-blast
E: Unable to locate package bio-linux-cd-hit
E: Unable to locate package bio-linux-rbs-finder
E: Unable to locate package bio-linux-transterm-hp
E: Unable to locate package bio-linux-catchall
E: Unable to locate package bio-linux-readseq
E: Unable to locate package bio-linux-oligoarray
E: Unable to locate package bio-linux-oligoarrayaux

Fatal error: local() encountered an error (return code 100) while executing 'sudo http_proxy=$http_proxy https_proxy=$https_proxy  bash -c "apt-get -y --force-yes install euca2ools s3cmd bio-linux-dotter bio-linux-mcl bio-linux-mummer bio-linux-pfaat bio-linux-prank bio-linux-squint bio-linux-t-coffee exonerate mafft muscle probcons wise bio-linux-artemis bio-linux-big-blast bio-linux-cd-hit bio-linux-rbs-finder bio-linux-transterm-hp mcl predictprotein tigr-glimmer bio-linux-catchall bio-linux-readseq primer3 ugene bio-linux-oligoarray bio-linux-oligoarrayaux fastx-toolkit last-align"'

Aborting.
local() encountered an error (return code 100) while executing 'sudo http_proxy=$http_proxy https_proxy=$https_proxy  bash -c "apt-get -y --force-yes install euca2ools s3cmd bio-linux-dotter bio-linux-mcl bio-linux-mummer bio-linux-pfaat bio-linux-prank bio-linux-squint bio-linux-t-coffee exonerate mafft muscle probcons wise bio-linux-artemis bio-linux-big-blast bio-linux-cd-hit bio-linux-rbs-finder bio-linux-transterm-hp mcl predictprotein tigr-glimmer bio-linux-catchall bio-linux-readseq primer3 ugene bio-linux-oligoarray bio-linux-oligoarrayaux fastx-toolkit last-align"'
staj@biolinux:~/tools/cloudbiolinux$

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. We hadn't yet brought the full CloudBioLinux install up to date with the latest changes from the Bio-Linux team. I pushed a fix which removes all the packages that are no longer supported, so if you re-build it will hopefully run more cleanly for you. Thanks again.
