### ISSUE TITLE
Adding BioInterchange

### ISSUE THREAD

**Issue by indiedotkim** [chapmanb/cloudbiolinux#204]
This is not really an issue per se, but I could not find clear contact info on CloudBioLinux's web-site.

I am the indie dev behind [BioInterchange 2](https://www.codamono.com/biointerchange/) and I would be thrilled if the software could be bundled with CloudBioLinux.

BioInterchange 2 is neither free nor open source. Having said that, there are 30-day free trial licenses available and peer-reviewers get free licenses upon request too.

Since I am already providing a Linux deb-package, installation should be easy for CloudBioLinux users. But then, including the software directly would give users even easier access to it. I plan to build the software often though (updates are free), so I am not sure whether that would be a problem in the CloudBioLinux release schedule.

Anyway, if there is interest to include the software, please comment here or get directly in touch with me at: kim@codamono.com

Thanks!

**Comment by chapmanb** [comment]
Joachim -- thanks for this. We're happy to include BioInterchange in the CloudBioLinux build scripts as long as you're fine with redistributing it. If you'll have a homebrew recipe available that would be the easiest way to pull it in. You might want to try submitting to homebrew-science, as this fits there. Once that's present in the taps we can add it to the homebrew recipes configuration file: https://github.com/chapmanb/cloudbiolinux/blob/master/config/packages-homebrew.yaml Thanks again.

**Comment by indiedotkim** [comment]
@chapmanb Awesome! Yes, I am fine with CloudBioLinux redistributing BioInterchange. Are you folks fine with me advertising that BioInterchange is part of CloudBioLinux (once it has been added)?

I do have a Homebrew-binary formula, but that is only an OS X build. Is there a Linuxbrew-binary repo too? I could not find one with a quick Google search...

Otherwise, I also have a Debian repo (amd64 build). On my web-site I suggest Linux installs like this:

    apt-get update
    apt-get install -y apt-transport-https python3.4
    echo "deb https://www.codamono.com/debs/ stable main" >> /etc/apt/sources.list
    apt-get update
    apt-get install -y --allow-unauthenticated biointerchange

Note that Python 3.4 is not really required, as long as users are fine with the basic functionality of BioInterchange and do not want to make use of its Python API.

**Comment by indiedotkim** [comment]
@chapmanb If my Homebrew-science formula gets accepted with this [pull request](https://github.com/Homebrew/homebrew-science/pull/2589), then it would be possible to use brew to install the Linux version too.

**Comment by indiedotkim** [comment]
@chapmanb It's done -- in Homebrew Science now.

    brew install homebrew/science/biointerchange

**Comment by chapmanb** [comment]
Thanks much for getting Biointerchange into homebrew science. That makes everything super easy on our side. I added Biointerchange to the list of packages installed by the default installation and everyone can get it in a custom flavor by adding `biointerchange` to the list of packages in their `packages-homebrew.yaml`. Thanks again.

**Comment by indiedotkim** [comment]
@chapmanb Thank you!

May I use the CloudBioLinux [logo](http://cloudbiolinux.org/images/logo.png) on my web-site to link to cloudbiolinux.org?

**Comment by chapmanb** [comment]
Absolutely, of course. Thanks again.
