### ISSUE TITLE
hg38 build files not available?

### ISSUE THREAD

**Issue by percyfal** [chapmanb/cloudbiolinux#205]
I just tried downloading hg38 using the following config:

```
  - dbkey: hg38
     name: Human (hg38) full
     annotations: [dbsnp, clinvar, mills_indels, 1000g_snps, 1000g_indels, 1000g_omni_snps, hapmap_snps, lcr]
```

Requesting e.g. index bowtie2 results in 

```
Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O hg38-bowtie2.tar.xz 'https://s3.amazonaws.com/biodata/genomes/hg38-bowtie2.tar.xz''
```

Requesting build hg19 works fine. Am I missing something here?

**Comment by chapmanb** [comment]
Per;
Right now we only support variation runs with bwa on hg38 and hg38-noalt, and haven't yet had the opportunity to test and support bowtie2 and other resources needed for RNA-seq runs. Specifically we haven't yet investigated how to tweak bowtie2 for alternative alleles and the impact that has on RNA-seq calling. The installation procedure should build an index by hand if you request bowtie2, but just won't have pre-built indexes for it. Hope this helps.

**Comment by percyfal** [comment]
Ok, thanks for the info. I must admit I hadn't really looked into the hg38 release that much yet but I've understood as much that there are quite some questions re reference choice to address. I need hg38 for a project now, any feedback you'd be interested in?

**Comment by chapmanb** [comment]
Per;
You need hg38 for an RNA-seq project? I'd suggest trying the `hg38-noalt` target which is the new 38 build without the alternative chromosomes. There is a pre-built index from the NCBI build (which is the same one linked from the bowtie2 page) we could provide in bcbio for this:

ftp://ftp.ncbi.nlm.nih.gov/genbank/genomes/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines/

Would that work? If so, I'll add it and we'd be happy for feedback with how it works. Thanks for trying this out.

**Comment by domibel** [comment]
The ftp link above is now broken.

The files have been moved into a archive location:
ftp://ftp.ncbi.nlm.nih.gov/genomes/archive/old_genbank/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines/

They keep them also under the new ftp location
ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/vertebrate_mammalian/Homo_sapiens/all_assembly_versions/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/

Do they have new GRCh38.p? patch builds for non alt aware aligner ? I don't see anything in
ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/vertebrate_mammalian/Homo_sapiens/all_assembly_versions/GCA_000001405.21_GRCh38.p6

**Comment by chapmanb** [comment]
Dominique -- thanks for the heads up on the URL changes. For bcbio and CloudBioLinux we're trying to standardize on hg38 (with alts) as that provides an improvement over hg38-noalt and hg19 for variant calling, and also enables HLA typing. Tooling for RNA-seq analysis on hg38 full is also starting to fall into place. In CloudBioLinux we use the 1000 genomes distribution right now, which has HLA alleles included: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/

Would hg38 work for your needs?

**Comment by domibel** [comment]
Thanks Brad, hg38 is fine, I posted the updated links just in case someone else is looking for it.
