### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Eduardo-Alves** [chapmanb/cloudbiolinux#215]
In cloudbiolinux/ggd-recipes/GRCh37/prioritize.yaml

instead of 
baseurl=https://s3.amazonaws.com/biodata/coverage/prioritize/prioritize-cancer-GRCh37-20150215.tar.gz

should be 20160215

baseurl=https://s3.amazonaws.com/biodata/coverage/prioritize/prioritize-cancer-GRCh37-20160215.tar.gz

**Comment by chapmanb** [comment]
Eduardo;
Thanks for the heads up and apologies about the mistake. If you remove the temporary cloudbiolinux download (`rm -rf tmpbcbio-install`) and re-update it should grab the latest CloudBioLinux and install cleanly.
