### ISSUE TITLE
picard invocation error

### ISSUE THREAD

**Issue by errontitus** [chapmanb/cloudbiolinux#217]
Running this command to download genomes:

fab -f data_fabfile.py -H localhost install_data_s3

I get the following error:

'-Xms500m' is not a valid command. See PicardCommandLine --help for more information.

Fatal error: local() encountered an error (return code 1) while executing 'picard -Xms500m -Xmx1g CreateSequenceDictionary REFERENCE=/mnt/biodata/genomes/phiX174/phix/seq/phix.fa OUTPUT=/mnt/biodata/genomes/phiX174/phix/seq/phix.dict'

Aborting.

---

Context: I'm using Mac OS X. I would eventually be interested in using bcbio+Docker on Mac. Looks like that would be a great platform. For now, I tried a CloudBioLinux install, but I noticed that there's some fragility with regard to python package names. It failed because age-metasv is not a valid python package name in my context. At that point, I scaled my ambitions back and am just installing tools singly using brew. After I installed a few basic NGS tools, I tried the genome download, and I am now stuck at the above error. Thanks!

**Comment by chapmanb** [comment]
Erron;
Sorry about the problems and confusion. CloudBioLinux is undergoing a bit of a transition, in part to be more friendly to alternative install environments like OSX. It supports a lot more desktop installs than initially envisioned by the name, so we've tried to migrate to help with that. Specifically, we're moving all of the tool installs to bioconda:

https://bioconda.github.io/

If you install picard (and any other bio tools you might like -- there are a lot of recipes ported: https://github.com/bioconda/bioconda-recipes) and re-run things shoudl work cleanly for you. The picard install from bioconda has a bit smarter shell script that handles setting memory, which the homebrew one does not.

Hope that helps get things going for you.

**Comment by errontitus** [comment]
Thanks so much! I switched over to bioconda to build my environment.

Fyi, the genome download still fails. It chugs through a few genomes with
no errors but then halts with a 404 error for this: wget --continue
--no-check-certificate -O hg38-bwa.tar.xz '
https://s3.amazonaws.com/biodata/genomes/hg38-bwa.tar.xz

Best,

Erron

**Comment by chapmanb** [comment]
Erron;
Sorry about the install troubles. I pushed a small change to CloudBioLinux (you can pull to your local version with git pull origin master) that changes the behavior of the `install_data` target, which is what you want to use:
```
fab -f data_fabfile.py -H localhost install_data
```
CloudBioLinux has a few different methods to install data and `install_data_s3` only tries to download pre-built genome indices on S3. We don't have these for every genome and the `install_data` retrieves from other public sources.

Hopefully this works cleanly for you and sorry again about the confusion. We're moving to a more standardized method for this but that's currently in progress. Hopefully longer term you'll have a cleaner experience with this.

**Comment by errontitus** [comment]
Hi Brad,

Thanks again. Your directing me to bioconda was critically helpful.

There is another downstream error (below). I think it's from the
mirbase.yaml recipe.

Note zcat on Mac OS X trying to append the ".Z" to an input
filename. Presumably a well-known Mac vs Linux issue, but here's additional
info just in case:
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/zcat.1.html.
And specifically, "When invoked as zcat, ``.Z'' will be appended to all
filenames that do not have that suffix."

That mirbase.yaml recipe is trying to do heroic work. It's a lot to attempt
in this context. Is the best thing for me to just remove or rename the
recipe files that I might not currently need?

Thanks.

Erron

[localhost] local: mv hg19-bwa.tar.xz /mnt/biodata/genomes/Hsapiens/hg19

[localhost] local: rm -rf
/var/folders/f2/c4mh2hr52pd6hmzyb89by91r0000gn/T/cloudbiolinux/6005c0fe-0ec6-323d-8531-a7207ed87080

[localhost] local: xz -dc hg19-bwa.tar.xz | tar -xvpf -

x bwa/

x bwa/hg19.fa.pac

x bwa/hg19.fa.amb

x bwa/hg19.fa.sa

x bwa/hg19.fa.ann

x bwa/hg19.fa.bwt

[localhost] local: rm -f hg19-bwa.tar.xz

Running GGD recipe: srnaseq

zcat: can't stat: tRNAs.txt.gz (tRNAs.txt.gz.Z): No such file or directory

Traceback (most recent call last):

  File
"/Users/errontitus/anaconda/lib/python2.7/site-packages/fabric/main.py",
line 743, in main

    *args, **kwargs

  File
"/Users/errontitus/anaconda/lib/python2.7/site-packages/fabric/tasks.py",
line 387, in execute

    multiprocessing

  File
"/Users/errontitus/anaconda/lib/python2.7/site-packages/fabric/tasks.py",
line 277, in _execute

    return task.run(*args, **kwargs)

  File
"/Users/errontitus/anaconda/lib/python2.7/site-packages/fabric/tasks.py",
line 174, in run

    return self.wrapped(*args, **kwargs)

  File "/Users/errontitus/Downloads/cloudbiolinux/data_fabfile.py", line
60, in install_data

    genomes.install_data(config_source)

  File
"/Users/errontitus/Downloads/cloudbiolinux/cloudbio/biodata/genomes.py",
line 345, in install_data

    _prep_genomes(env, genomes, genome_indexes, ready_approaches)

  File
"/Users/errontitus/Downloads/cloudbiolinux/cloudbio/biodata/genomes.py",
line 474, in _prep_genomes

    retrieve_fn(env, manager, gid, idx)

  File
"/Users/errontitus/Downloads/cloudbiolinux/cloudbio/biodata/genomes.py",
line 796, in _install_with_ggd

    ggd.install_recipe(env.cwd, recipe_file)

  File "/Users/errontitus/Downloads/cloudbiolinux/cloudbio/biodata/ggd.py",
line 30, in install_recipe

    recipe["recipe"]["full"]["recipe_type"])

  File "/Users/errontitus/Downloads/cloudbiolinux/cloudbio/biodata/ggd.py",
line 62, in _run_recipe

    subprocess.check_output(["bash", run_file])

  File "/Users/errontitus/anaconda/lib/python2.7/subprocess.py", line 573,
in check_output

    raise CalledProcessError(retcode, cmd, output=output)

subprocess.CalledProcessError: Command '['bash',
'/mnt/biodata/genomes/Hsapiens/hg19/txtmp/ggd-run.sh']' returned non-zero
exit status 1

**Comment by chapmanb** [comment]
Erron;
Sorry about the issues there -- these are definitely not all tested on OSX so look like they'll need some tweaking.

Practically if you don't need this resource you can remove it from your biodata.yaml configuration file:

https://github.com/chapmanb/cloudbiolinux/blob/master/config/biodata.yaml

The configuration defines everything you could install but the idea is to edit it to include the genomes and annotations you actually need to do your work. Hope adjusting this gets you to the type of installation your looking for.
