### ISSUE TITLE
dbNSFP for hg38

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/cloudbiolinux#231]
Hi Brad, 

I see cloudbiolinux doesn't include dbNSFP for hg38. Would it be possible to add this in? Or does this somehow get handled by sourcing the yaml file for GRCh37?

As I see it, it would be usefull to download and process the file once, and then generate an index useable for each build. 

Do you think this is manageable?

Thanks
M

**Comment by chapmanb** [comment]
We can definitely make this available and could re-use the recipe for hg19/GRCh37 changing the columns we index on. I left a note in the current recipe about the columns to use for tabix indexing. Before adding this, I wanted to confirm that the recent fixes resolved the VEP/dbNSFP issues everyone was seeing. Does it work okay in your testing?

Unfortunately we'll have to download this twice as we don't have any current mechanisms to re-use files across genome builds like this, but we can at least share the entire recipe to avoid needing to re-write it.

Thanks again for the feedback and thoughts.

**Comment by matthdsm** [comment]
Hi @chapmanb , 

sorry this took a while, but the fix for dbNSFPv3.2a and GRCh37 doesn't seem to work for me.
I'm getting to following error while trying to tabix the file.

```
$ tabix -s 8 -b 9 -e 9 -c '#' dbNSFP.txt.gz                                                                                                                                                                                                               
 [E::hts_idx_push] unsorted positions
 tbx_index_build failed: dbNSFP.txt.gz
```
I think this is because there are some positions which are annotated in hg38 are not available in GRCH37. The missing GRCh37 positions are then notated as `.`

Perhaps its possible to remove those lines during the initial parsing? I think that should solve the issue.

I think for dbNSFP in VEP with GRCH37, we're going to have to do some modifications to the raw data, or just revert the version to dbNSFPv2.9.1, which is the latest build based on GRCh37.
I know reverting to an older version isn't the most desirable way to fix something, but the contents of dbNSFP 2.9.1 are also quite up to date, and in a way its kind of logical that if you want to use an older genome build, you get somewhat older reference data.

Anyway, I'd like your thoughts on this? I think it's better to have older data instead of just plain wrong data.

Thanks
M

**Comment by chapmanb** [comment]
Thanks for following up on this. I don't think moving backwards is the best approach here, since there is no guarantee those will be supported longer term. Apologies, I should have caught this issue. dbNSFP is frustrating to work with, I need to spin up an instance with enough disk space to test installation fully with. I pushed a fix which sorts by hg19 position prior to tabix indexing and will hopefully resolve this. It also tries to do a better job of streaming to avoid some disk space issues since we now need to have temporary files for the sorting. Thanks again for testing and hope this latest iteration fixes it.

**Comment by matthdsm** [comment]
I fully agree dbNSFP is a pain in the ass to process. Useful resource for annotation though. I'll give the fix a whirl and get back to you if I get some results.

Thank you again for your work, it's very valuable to us.
M
