### ISSUE TITLE
ExAC vcf files for hg38 have changed url

### ISSUE THREAD

**Issue by vandalum** [chapmanb/cloudbiolinux#248]
The url listed in ggd-recipes/hg38/exac.yaml does no longer exist.  
Is the following url is correct?
http://ftp.ensembl.org/pub/data_files/homo_sapiens/GRCh38/variation_genotype/ExAC.0.3.GRCh38.vcf.gz

**Comment by chapmanb** [comment]
Guus -- thanks so much for letting us know about the changed URL. I adjusted the recipe so it should work cleanly for installs now. Much appreciated.
