### ISSUE TITLE
clinvar versioning

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/cloudbiolinux#257]
Hi Brad,

As we're coming closer to the point where we need to get our accreditation, we're starting to write pin and write out everything about the pipeline. Since we need some strict versioning I have a quick question.
How would you feel about adding the version number to the clinvar file filename? This would only require a small change to the ggd recipe, and we could place a symlink in the same directory with the more general `clinvar.vcf.gz` name. That way, it's easier to track which version is in use by just checking the filename.

If you're ok with this, I'll create a PR with the required modifications. I'll also do the same for all other datasets that have an unversioned filename ( Clinvar/dbNSFP/esp/...)

Cheers
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for this discussion. I'd rather have general names for the resources for a couple of reasons:

- We don't need to synchronize and update configurations every time we update a version. This was a constant source of small bugs and annoyances when we embedded versions in file names previously.
- Updated systems don't end up with a lot of old versions taking up space as new ones get downloaded.

I'm absolutely agreed it's important to track versions, and we have a `versions.csv` file in every genome directory that has the exact version used. bcbio uses this file to generate a `data_versions.csv` file that lists these for a specific run so you can go back and retrace an analysis to know exactly what was used. Would those resources work for what you need?

**Comment by matthdsm** [comment]
good enough for me! Should've thought about that one myself.

Cheers
M
