### ISSUE TITLE
rn6-twobit.tar.xz is not avaiable

### ISSUE THREAD

**Issue by biocyberman** [chapmanb/cloudbiolinux#259]
This file couldn't be downloaded:
https://s3.amazonaws.com/biodata/genomes/rn6-twobit.tar.xz

**Comment by chapmanb** [comment]
Vang;
Sorry about the issue. Could you paste the full error you're seeing? We don't have pre-built indices for many resources but the installer should try to download, report it can't find them, and then move on to building them locally. Is it possible you're getting an error from the downstream build?

**Comment by biocyberman** [comment]
Hi Brad,
This is the stderr of this command:
`bcbio_nextgen.py upgrade -u development --datatarget ericscript --gitrepo https://github.com/biocyberman/bcbio-nextgen.git --revision ericscript`
(by the way, I am testing the --gitrepo parameter to install bcbio-nextgen from its fork).

```
INFO: Genome preparation method ggd failed, trying next
INFO: Genome preparation method ggd failed, trying next
INFO: Downloading genome from s3: rn6 twobit
INFO: Downloading genome from s3: rn6 twobit
[localhost] local: pwd
[localhost] local: echo $HOME
[localhost] local: wget --continue --no-check-certificate -O rn6-twobit.tar.xz 'https://s3.amazonaws.com/biodata/genomes/rn6-twobit.tar.xz'
--2017-11-02 11:44:40--  https://s3.amazonaws.com/biodata/genomes/rn6-twobit.tar.xz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.131.181
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.131.181|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-11-02 11:44:41 ERROR 404: Not Found.


Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O rn6-twobit.tar.xz 'https://s3.amazonaws.com/biodata/genomes/rn6-twobit.tar.xz''

INFO: Genome preparation method s3 failed, trying next
INFO: Genome preparation method s3 failed, trying next
INFO: Preparing genome rn6 with index twobit
INFO: Preparing genome rn6 with index twobit
bcbio-nextgen data upgrade complete.
```

**Comment by chapmanb** [comment]
Vang;
Thanks for following up. It looks like it successfully build the index locally and then finished wihout any problems so this is not a problem. Sorry for the scary warning message and thanks for reporting.

**Comment by biocyberman** [comment]
Yeah, I was looking at the `ERROR 404: Not Found.` and also testing the link manually via web browser. I thought the error was something unexpected.
