### ISSUE TITLE
Update GRCh37 and GRCh38 cosmic

### ISSUE THREAD

**Issue by lemdcock** [chapmanb/cloudbiolinux#262]
Hi,

Would it be possible to update the cosmic vcf files of GRCh37? And add those for GRCh38/hg38?

Kind regards

**Comment by chapmanb** [comment]
Thanks much for the suggestions. Unfortunately automating COSMIC installs is difficult now as the license terms do not allow redistribution so we can't automate this as part of cloudbiolinux (http://cancer.sanger.ac.uk/cosmic/license). Manually adding these is probably your best bet at this point, although I'm open to any ideas that would work to improve accessibility of this resource.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks for the answer. Could you give us some pointers on how we best go about manually adding this dataset? We'd like to use it as one of the reference files for Mutect2.

Cheers
M

**Comment by chapmanb** [comment]
Matthias;
Manually updating this for build 37 would require replacing the files bcbio downloads with the latest versions that the resources point with:

https://github.com/chapmanb/bcbio-nextgen/blob/master/config/genomes/hg19-resources.yaml#L14

and adding something equivalent for hg38. Practically I think the steps we should take are:

- Rename the current download to be something more general (without the version number) and update the pointer in the resources YAML.
- Add an equivalent pointer in hg38 resources, but without any related download.
- Document how to download and prep the inputs from COSMIC.

I'd be happy to help with this if you're able to look at it immediately or can work on it after clearing up some time. Thanks again for this discussion.

**Comment by matthdsm** [comment]
Hi Brad,

Would be nice! I'll look into it together with my my colleague Laurenz if we have some spare time.

Cheers
M

**Comment by lemdcock** [comment]
Hi,

Since Cosmic provides two .vcf files, one for coding and one for non-coding mutations, I was wondering which one you used. Or did you combine the two .vcf files into one larger file? 

Kind regards,
Laurenz

**Comment by chapmanb** [comment]
Laurenz and Matthias;
Thanks again for this discussion and work. To make it easier to install and update cosmic in bcbio I refreshed our older preparation script so it now handles the new sftp downloads with authentication and copies over the outputs into bcbio. The approach is documented in the installation, building off what you had added:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#customizing-data-installation

Please let us know if you run into any issues and hope this makes it easy to keep cosmic updated in a bcbio installation.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks a lot, the preparation script will come in very handy! We'll be sure to give it a try and let you know if anything comes up!

Cheers
M
