### ISSUE TITLE
Prepare_cosmic.py when only grch37 is present 

### ISSUE THREAD

**Issue by apastore** [chapmanb/cloudbiolinux#265]
Hi Brad, I have only grch37 and no hg19 installed. 
Wenn I run prepare_cosmic.py it complain that genome/hg19/seq is not there. 

I am not at my workstation now. But if you need I can send you the exact error message. 

Thanks lot!
Alessandro 

        if bcbio_build == "GRCh37":
            bcbio_base = os.path.join(bcbio_genome_dir, "genomes", "Hsapiens", bcbio_build)
            if not os.path.exists(bcbio_base):
                continue
            out_dir = utils.safe_makedir(os.path.join("v%s" % cosmic_version, "bcbio_ready", "hg19"))
            out_file = os.path.join(out_dir, "cosmic.vcf.gz")
            hg19_cosmic = map_coords_to_ucsc(ready_cosmic, bcbio_ref, out_file)
            utils.copy_plus(hg19_cosmic, os.path.join(bcbio_base, "variation", os.path.basename(ready_cosmic)))

**Comment by chapmanb** [comment]
Alessandro -- thanks for the heads up and apologies about the issue. I fixed the typo and it should hopefully correctly skip processing the hg19 version now if you re-run. Thanks again.

**Comment by apastore** [comment]
Thanks! I have to manual copy the cosmic-prep/v83/bcbio_ready/GRCh37/* in the bcbio/genome/GRCh37/variation ?

**Comment by chapmanb** [comment]
It should copy it over for you, please let me know if not. The change avoids trying and copying over the hg19 translated version. Hope this works for you.

**Comment by apastore** [comment]
Exactly! Strange it did not copy, and just move it manually. Hope this not became an issue later. 
Thanks
