### ISSUE TITLE
gnomad exome issue

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/cloudbiolinux#281]
Hi Brad, 

I'm not sure if it's just me, but I noticed that the gnomad exome vcf file is only about 500mb post processing. Since the original file is 5GB+ this seems fishy to me.

Could you check your install for size?
Thanks
M

**Comment by pfpjs** [comment]
Hi @matthdsm, @chapmanb, @naumenko-sa,

I'm getting the same truncated files as @matthdsm, but only for GRCh37 and hg38, while hg19 completed successfully.

Looking at the ggd recipes, hg19 uses `wget` to fetch the gnomad VCFs (gnomad_exome and gnomad_genome), while GRCh37 and hg38 both use the URL directly as an argument to `vt decompose`.

I've tried rerunning the GRCh37 and hg38 recipes three times now, and they always fail at roughly (but not exactly) the same spot - leaving me with a ~400Mb `gnomad_exome.vcf.gz` file and a ~340Mb `gnomad_genome.vcf.gz` file.

For reference, here are the sizes of the hg19 version of these two files:

`gnomad_exome.vcf.gz: 5391108579 bytes`
`gnomad_genome.vcf.gz: 26405145616 bytes`

-- Paulo

**Comment by naumenko-sa** [comment]
Hi Matthias @matthdsm  and Paulo @pfpjs !

Thanks for reporting the issue and pointing out how to fix it!
I indeed see the same effect on my system.

I pushed a fix in my fork https://github.com/naumenko-sa/cloudbiolinux
and created a pull request for Brad @chapmanb.

Please let me know if this resolved the issue!
Sergey

**Comment by chapmanb** [comment]
Thanks Sergey -- this got pulled and is available now. Thank you all for testing and reporting and let us know if you hit any other problems.

**Comment by matthdsm** [comment]
Hi guys,

I was doing some digging and turns out we're making things too hard on ourselves. The annotation works just as well without decomposing/normalizing the gnomad vcf. What are your opinions on this?

Cheers
M

**Comment by pfpjs** [comment]
Hi @naumenko-sa,

GRCh37 `gnomad_exome.vcf.gz` completed sucessfully, thank you!

However, `gnomad_genome.vcf.gz` also needs the wget "treatment". Thanks!
