### ISSUE TITLE
Feature request: Update Drosophila genome build to support dm6

### ISSUE THREAD

**Issue by mjsteinbaugh** [chapmanb/cloudbiolinux#292]
Hi @chapmanb, I'm using the pre-built reference *Drosophila* genome for a few experiments, and it'd be helpful to add support for dm6 (Aug 2014) in place of the current dm3 (Apr 2006) build. How do I go about submitting a pull request for a genome build update?

Also, bcbio has some genome-specific calculations for ChIP-seq that need to be accounted for, so that would need to be updated as well for dm6 (see [`macs2.py`](https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/chipseq/macs2.py#L15) for example).

For reference, here are some relevant files:

- [`biodata.yaml`](https://github.com/chapmanb/cloudbiolinux/blob/master/config/biodata.yaml#L78)
- [`genomes.py`](https://github.com/chapmanb/cloudbiolinux/blob/master/cloudbio/biodata/genomes.py#L280)

**Comment by roryk** [comment]
Hi Mike,

I added support for BDGP6 and build the transcriptome against Ensembl release 95, so you should be all good to go for upgrading.

**Comment by mjsteinbaugh** [comment]
Nice thanks @roryk! I'm using this for ChIP-seq with macs2 – do we need to update the HS genome size value? ([`macs2.py`](https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/chipseq/macs2.py#L15))

**Comment by roryk** [comment]
Yep-- let me fix that so we don't have to hardcode the values anymore.

**Comment by roryk** [comment]
Thanks-- I see in the code, it just calculates the genome size from the reference FASTA if it isn't hardcoded in there already, so this should be all set without the change.

**Comment by mjsteinbaugh** [comment]
Perfect thanks @roryk
