### ISSUE TITLE
mirbase GFF file not installed for mmu even if it is present

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/cloudbiolinux#293]
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/mm10/mirbase.yaml is missing the download step for the GFF file in mirbase. When running bcbio for smallrnaseq, its absence will skip some analyses. As the file is available on mirbase, it should be downloaded.

**Comment by roryk** [comment]
Thanks! Do you think you could pull request on cloudbiolinux with that addition?

**Comment by lpantano** [comment]
Hi @lbeltrame,

thanks for telling us that. It missed that.

I think it should be fix now. Can you try to update the srna data?
