### ISSUE TITLE
gnomad_exome ggb randomly fails on chr1

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/cloudbiolinux#298]
Dear users of cloudbiolinux!

I have to warn you that the recipe 
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/GRCh37/gnomad_exome.yaml

worked well on a test of (chr21,chr22, X, Y), but fails randomly with a pipe error during the full-scale installation, after writing ~200M of the output file for chr1.

Sorry about that. I'm trying to investigate, why. 

For now, I see that the guilty filter in the pipe is `vt rminfo` with a large number of fields to remove. When I exclude that filter, the recipe works. 

As a solution, I'm testing 
`bcftools annotate -x "^list_of_fields_to_keep"` as an alternative filter.

Sergey

**Comment by chapmanb** [comment]
Sergey;
Thanks for working on this and for the heads up. Happy to convert over to bcftools annotate for this if it works more cleanly in your tests. I appreciate you testing and working on the fixes.

**Comment by naumenko-sa** [comment]
Hi Brad! 

The problem is definitely gone with the help of bcftools in chr1 test. Please merge and I will run the entire installation to make sure everything works for all chr.
https://github.com/chapmanb/cloudbiolinux/pull/299

Sergey

**Comment by chapmanb** [comment]
Thanks so much, merged your fix. Fingers crossed it's all running cleanly now.

**Comment by naumenko-sa** [comment]
It works, but it is really slow. 2 chrs in 2 days for gnomad_genome for me. I will be lucky if the installation finishes in 1 week. Probably, we just need to push the resulting file in the cloud to make life easier for other people.

**Comment by lbeltrame** [comment]
The script also fails for downloading exomes:

```
2019-05-10 12:37:58 (347 KB/s) - 'gnomad.exomes.r2.1.sites.chr1_noVEP.vcf.gz.tbi' saved [90750/90750]

/opt/bcbio/genomes/Hsapiens/hg19/txtmp/ggd-run.sh: line 23: fields_to_keep: unbound variable
> gsort version 0.0.6
```
