### ISSUE TITLE
bismark_indices.loc missing

### ISSUE THREAD

**Issue by gcampanella** [chapmanb/cloudbiolinux#318]
This is related to PRs #313 (which added [Bismark](https://www.bioinformatics.babraham.ac.uk/projects/bismark/) to `ngs_pipeline_minimal`), #316 and #317 (which added GGD recipes for the one-time genome preparation step required by Bismark).

In 1e09aed0bd7a35bf02bee2e75c2b4dd1dbfa4b53 I added some lines to `galaxy.py` hoping that `bismark_indices.loc` would be generated automatically, but this doesn't seem to be the case.

I'm not sure I understand how `*.loc` file are created. If you could point me in the right direction, I'd be happy to work on another PR to fix this.

**Comment by chapmanb** [comment]
Gianluca;
Thanks much for working on this and sorry about the many places to adjust to add new indices. There are quite a few different ways to do it that developed historically, so a few places to adjust. I've added in the bits to point at the output directory from your GGD directories which I hope will get the indexes created correctly for you. Please let us know if you hit any other issues.

**Comment by gcampanella** [comment]
That's great, thanks so much @chapmanb! :slightly_smiling_face:
