### ISSUE TITLE
limit conda environments

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/cloudbiolinux#340]
Hi,

I was wondering if it'd be possible to put an effort together to limit the conda evironments currently installed buy cloudbiolinux.

I suppose the following steps are pretty easy targets
- bump default python to 3.7
- eliminate python 3 env in favor of the default bcbio env (also python 3)
- check pkgs in python2 env and see if they can be moved to the default env

I you point me in the right direction, I'll prepare a PR with what I suppose is viable.

Thanks
M

**Comment by naumenko-sa** [comment]
that was finally achieved in here: https://github.com/chapmanb/cloudbiolinux/pull/387
